name: indistinction
favicon: null
layout_spectrum: 0.5373331671580672
typography_spectrum: 0.5268598459661007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3797988402657211
  lightness: 0.07258911686949432
  saturation: 0.47097024344839156
  rhythmicContrast: 0.9184538628906012
purpose: []
